# This workflow validates the Gemini CLI extension in the repository
name: Validate Data Commons Gemini CLI Extension

# Run on pushes to the main branch and any pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - run: echo "CI workflow executed"
